### ISSUE TITLE
自己加了一些字典会报错,似乎兼容性不太好

### ISSUE THREAD

**Issue by Angus-Team** [corunb/Dirscan#1]
![image](https://user-images.githubusercontent.com/103045627/204124932-9e47356f-2366-4075-949c-8a5c4dd15b39.png)

**Comment by Angus-Team** [comment]
[10296/12593]  81%  panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x64f68b]

goroutine 34 [running]:
Dirscan/config.Request({0xc00001a5ac, 0x3}, {0x7ffc772b43f6, 0x1b}, {0xc000472360, 0x15})
        Dirscan/config/scan.go:202 +0x36b
Dirscan/config.GetScan({0x7ffc772b43f6, 0x1b}, 0x0?, 0x0?, 0x0?)
        Dirscan/config/scan.go:137 +0xd6
created by Dirscan/config.Scans
        Dirscan/config/scan.go:56 +0x1be

**Comment by corunb** [comment]
是否是最新版呢？字典格式确实是否无误？字典前都需要加  /

**Comment by Angus-Team** [comment]
是最新版的,
就有一些编码的路径会报错.总体还行吧
类似于这样的编码会报错:
/..%u2215..%u2215/etc/passwd
/..%u2215..%u2215..%u2215/etc/passwd
/..%u2215..%u2215..%u2215..%u2215/etc/passwd
/..%u2215..%u2215..%u2215..%u2215..%u2215/etc/passwd
/..%u2215..%u2215..%u2215..%u2215..%u2215..%u2215/etc/passwd
/..%u2215..%u2215..%u2215..%u2215..%u2215..%u2215..%u2215/etc/passwd
/..%u2215..%u2215..%u2215..%u2215..%u2215..%u2215..%u2215..%u2215/etc/passwd
/%uff0e%uff0e//etc/passwd
/%uff0e%uff0e/%uff0e%uff0e//etc/passwd
/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e//etc/passwd
/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e//etc/passwd
/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e//etc/passwd
/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e//etc/passwd
/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e//etc/passwd
/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e//etc/passwd
/%uff0e%uff0e%u2215/etc/passwd
/%uff0e%uff0e%u2215%uff0e%uff0e%u2215/etc/passwd
/%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215/etc/passwd
/%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215/etc/passwd
/%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215/etc/passwd
/%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215/etc/passwd
/%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215/etc/passwd
/%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215%uff0e%uff0e%u2215/etc/passwd

**Comment by corunb** [comment]
感谢提交，后续会优化一下

**Comment by corunb** [comment]
@Angus-Team v1.4.9版本已修复该bug
