### ISSUE TITLE
一些功能上的建议

### ISSUE THREAD

**Issue by duokebei** [corunb/Dirscan#2]
1、例如过滤响应长度，我看扫描显示的，有的以B结尾，有些以KB结尾，可以统一用B结尾，然后增加一个选项，过滤某个响应长度的url，像webpack类型的站点，很多都是一样的长度，这种是无意义的。
2、关于递归扫描，希望可以指定递归几层，默认不递归。

**Comment by corunb** [comment]
好的，感谢师傅提的意见，最近身体不适，等后续总结归纳然后更新

**Comment by able9527** [comment]
师傅好，借楼也提下建议
1、有考虑过智能识别或者设置阈值来过滤那些同一响应长度的路径吗，比如添加个参数用户自定义设置阈值-x 5这样子，要是5个路径返回相同长度的响应，后续该长度的直接过滤掉
2、手动递归扫描，显示访问url，好像是bug @corunb 
就像这样
![image](https://user-images.githubusercontent.com/59350511/220086750-4f979ef6-4962-42db-9cd0-82bc0760b047.png)
其实后面还有个/pc路径，但是工具从/m后就无法访问目标了

**Comment by corunb** [comment]
@ [able9527](https://github.com/able9527) 针对第一个问题，我进行了结果优化，你试试看
