### ISSUE TITLE
使用导出的问题

### ISSUE THREAD

**Issue by hackerxj007** [corunb/Dirscan#4]
导出的结果建议把文件结果的大小显示，因为如果批量扫描的话看不到多大会容易有误报，然后再可以再加个 可选的 （备份扫描功能 比如：www.baidu.com 取 baidu 和 www 进行 zip gz 7z等格式进行扫描  或者是字典加上类似的($host1)，($host2)来匹配

**Comment by hackerxj007** [comment]
if respCode >= 200 && respCode < 300 {
		Urlpath := url + path
		color.Green.Printf("\r%v     [%v]     %v    \t- %v \n", Time, respCode, Bodylen, Urlpath)
		Write(Time+"     "+"["+strconv.Itoa(respCode)+"] ["+Bodylen+"] "+Urlpath, url)

已经解决

**Comment by corunb** [comment]
感谢提交，后续会加上的
