### ISSUE TITLE
能否实时保存一下结果，还有字典比较大会报错。

### ISSUE THREAD

**Issue by hackerissb** [corunb/Dirscan#7]
![image](https://github.com/corunb/Dirscan/assets/10737138/784e45f7-f441-4006-b10d-20ddb1e6527e)
字典比较大，手动暂停是没结果数据的，能不能每隔一段时间就自动保存一下。

**Comment by hackerissb** [comment]
![image](https://github.com/corunb/Dirscan/assets/10737138/34380b2d-d26f-4c41-838a-6dabfe337769)

**Comment by corunb** [comment]
结果数据是扫到了，就会立即写入的；字典比较大时这个我再看看
